In [1]:
import k3d
import numpy as np
from k3d.colormaps import matplotlib_color_maps
from k3d.helpers import map_colors
from numpy.linalg import norm
r0 = np.array([0, 0, 0])
f = np.array([0, 1, 0])

In [3]:
import k3d
import numpy as np
from k3d import matplotlib_color_maps

data = np.load('/Users/gabrielaniechwiadowicz/Documents/GitHub/MicroWorld/MicroWorld/output.npz', allow_pickle=True)
#data = np.load('/Users/gabrielaniechwiadowicz/FUW/Stokeslets/Plots notebooks/output_22.npz', allow_pickle=True)
data.files
lines = data['arr_0']
print(data['arr_0'])

[[-3.896836889856024 -3.8905134446503986 0.0]
 [-3.893672335304027 -3.8810273713006676 0.0]
 [-3.8905062459404864 -3.8715418101185253 0.0]
 ...
 [3.897752126481204 3.8933563498215347 0.0]
 [3.9009147244680347 3.9028430760089923 0.0]
 [None None None]]


In [4]:
plt_streamlines = k3d.line(lines,
                           width=0.01,
                           )

"""plt_mesh = k3d.mesh(vertices, indices,
                    opacity=0.25,
                    wireframe=True,
                    color=0x0002)"""

plot = k3d.plot(grid_visible=True)
plot += plt_streamlines
#plot += plt_mesh
plot.display()

plot.camera = [0.0705, 0.0411, 0.0538,
               0.0511, 0.0391, 0.0493,
               -0.0798, 0.9872, 0.1265]

/Users/gabrielaniechwiadowicz/anaconda3/lib/python3.10/site-packages/traittypes/traittypes.py:97: UserWarning: Given trait value dtype "object" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


Output()

In [5]:

data2 = np.load('/Users/gabrielaniechwiadowicz/downloads/streamlines_data.npz', allow_pickle=True)
data2.files
lines2 = data2['lines'] 
print(lines2)
file = '//Users/gabrielaniechwiadowicz/Documents/GitHub/MicroWorld/Obiektowo/output.npz'
with open(file, 'w') as f:
    for i in lines2:
        print(i, file=f)
#well u mnie jest problem z wymiarem tego

[[0.0504883  0.0279593  0.0506036 ]
 [0.05048523 0.02803267 0.05059951]
 [0.05047622 0.02810528 0.0505916 ]
 ...
 [0.05114238 0.02810335 0.05400866]
 [0.05111146 0.02816993 0.05401351]
 [       nan        nan        nan]]


FileNotFoundError: [Errno 2] No such file or directory: '//Users/gabrielaniechwiadowicz/Documents/GitHub/MicroWorld/Obiektowo/output.npz'