In [1]:
import k3d
import numpy as np
from k3d.colormaps import matplotlib_color_maps
from k3d.helpers import map_colors
from numpy.linalg import norm
r0 = np.array([0, 0, 0])
f = np.array([0, 1, 0])

def stokeslet(f, r0, mX, mY, mZ):
     
    Id = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    
    r = np.array([mX - r0[0], mY - r0[1], mZ - r0[2]])

    Idf = np.dot(Id, f)

    rTf = (r * f[:, np.newaxis, np.newaxis, np.newaxis]).sum(axis=0)

    rrTf = (r * rTf[np.newaxis,])

    modr = np.sqrt(r[0]**2 + r[1]**2 + r[2]**2)

    u, v, w = Idf[:, np.newaxis, np.newaxis, np.newaxis] / modr + rrTf / modr**3. 
    
    return [u, v, w]


a = 5
b = 10
xx = np.linspace(-a, a, b)
yy = np.linspace(-a, a, b)
zz = np.linspace(-a, a, b)

xx, yy, zz = np.meshgrid(xx, yy, zz)

u, v, w = stokeslet(f, r0, xx, yy, zz)

print("first: ", u.shape)


print("sceond: ", np.array([v,u,w]).T.shape)

vectors = np.array([v,u,w]).T.astype(np.float32)

print(vectors.reshape(-1, 3).size)

norms = np.apply_along_axis(norm, 1, vectors.reshape(-1, 3))

plt_vector_field = k3d.vector_field(vectors,
                                    head_size=1.5,
                                    scale=2,
                                    #bounds=[10**(-1), 10**(1), 10**(-1), 10**(1), 10**(-1), 10**(1)] coś tu ze skalą zdecydowanie nie działa
                                    )

colors = map_colors(norms, matplotlib_color_maps.Inferno).astype(np.uint32)
plt_vector_field.colors = np.repeat(colors, 2)

plot = k3d.plot()
plot += plt_vector_field

plot.display()

Z = np.sqrt(u**2+v**2+w**2)
lines = np.array([ u, v, w])
print('here', u.shape)
np.savez('attempt_3d_1', Z)
np.savez('attempt_3d_3', lines)

first:  (10, 10, 10)
sceond:  (10, 10, 10, 3)
3000


Output()

here (10, 10, 10)


In [8]:
import k3d
import numpy as np
from k3d import matplotlib_color_maps

data = np.load('/Users/gabrielaniechwiadowicz/Documents/GitHub/MicroWorld/Obiektowo/output.npz', allow_pickle=True)
#data = np.load('/Users/gabrielaniechwiadowicz/FUW/Stokeslets/Plots notebooks/output_22.npz', allow_pickle=True)
data.files
lines = data['arr_0']

print(data['arr_0'])






[[-3.896836889856024 -3.8905134446503986 0.0]
 [-3.893672335304027 -3.8810273713006676 0.0]
 [-3.8905062459404864 -3.8715418101185253 0.0]
 ...
 [3.897752126481204 3.8933563498215347 0.0]
 [3.9009147244680347 3.9028430760089923 0.0]
 [None None None]]


In [10]:
plt_streamlines = k3d.line(lines,
                           width=0.01,
                           )

"""plt_mesh = k3d.mesh(vertices, indices,
                    opacity=0.25,
                    wireframe=True,
                    color=0x0002)"""

plot = k3d.plot(grid_visible=True)
plot += plt_streamlines
#plot += plt_mesh
plot.display()

plot.camera = [0.0705, 0.0411, 0.0538,
               0.0511, 0.0391, 0.0493,
               -0.0798, 0.9872, 0.1265]

Output()

In [3]:

data2 = np.load('/Users/gabrielaniechwiadowicz/downloads/streamlines_data.npz', allow_pickle=True)
data2.files
lines2 = data2['lines'] 
print(lines2)
file = '//Users/gabrielaniechwiadowicz/Documents/GitHub/MicroWorld/Obiektowo/output.npz'
with open(file, 'w') as f:
    for i in lines2:
        print(i, file=f)
#well u mnie jest problem z wymiarem tego

[[0.0504883  0.0279593  0.0506036 ]
 [0.05048523 0.02803267 0.05059951]
 [0.05047622 0.02810528 0.0505916 ]
 ...
 [0.05114238 0.02810335 0.05400866]
 [0.05111146 0.02816993 0.05401351]
 [       nan        nan        nan]]
